root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api.exe ./cmd/api"
  bin = "tmp/api.exe"
  delay = 300
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true